config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  https_constraint = (Rails.env.production? ? {protocol: 'https://'} : {})
  http_catchall    = (Rails.env.production? ? {protocol: 'http://'}  : -> (params, request) {false})

  namespace :api, path: "api", constraints: https_constraint, defaults: { format: 'json' } do
    scope module: :v2, constraints: ApiConstraints.new(version: 2) do
    end
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :devices do
        resources :device_settings, path: 'settings', only: [:index] do
          collection do
            post :bulk_update
          end
        end
        resources :metrics do
          resources :measures
          resources :alerts
        end
        resources :parameters
        resources :strips, only: [:create, :show]
        resources :log_entries, path: 'logs', only: [:create, :index]
        post :brain_upgrade, to: 'brain_upgrade#upgrade'
        post :brain_rollback,  to: "brain_upgrade#rollback"
      end
      namespace :app, path: 'app' do
        post :registration,  to: 'registration#create'
        post :login,         to: 'login#create'
        post :push_update,   to: 'push#create'
      end
    end
  end

  namespace :admin, path: "pastouch", constraints: https_constraint do
    resources :devices do
      member do
        get ':metric', to: 'metrics#show', metric: /(PH|WTEMP|WVOL|ATEMP|AHUM|LCYC|UCYC|NO2|NO3|NH4|GH|KH)/, as: 'metric'
      end
      resources :device_settings do
        patch :prolong_date, to: 'device_settings#prolong_date', on: :member
      end
      resources :log_entries, path: 'logs', only: :index
      resources :device_permissions, path: 'owners'
    end
    resources :users
    mount Resque::Server, at: '/jobs', as: 'jobs'
    root 'devices#index'
  end

  devise_for :users, class_name: 'Risebox::Core::User', path: "account", path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :account, path: "account", constraints: https_constraint do
    get :sso, to: "sso#sso"
  end

  post :sign, to: "signing#sign"
  get :form,  to: "signing#form"

  root 'home#index'

end

app/views/admin/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to image_tag('admin/logo.png', size: '20x20'), admin_root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><%= link_to 'Users', admin_users_path %></li>
            <li><%= link_to 'Devices', admin_devices_path %></li>
        </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div id="flash" class="flash">
    <% if notice.present? %><div class="notice"><%= notice %></div><% end %>
    <% if alert.present? %><div class="alert"><%= alert %></div><% end %>
</div>

<ol class="breadcrumb">
    <li class="<%= 'active' if breadcrumb_max_level == 1 %>"><a href="<%= breadcrumb_path(1) %>"><%= breadcrumb_title(1) %></a></li>
    <% if breadcrumb_max_level > 1 %>
        <li class="<%= 'active' if breadcrumb_max_level == 2 %>"><a href="<%= breadcrumb_path(2) %>"><%= breadcrumb_title(2) %></a></li>
    <% end %>
    <% if breadcrumb_max_level > 2 %>
        <li class="<%= 'active' if breadcrumb_max_level == 3 %>"><a href="<%= breadcrumb_path(3) %>"><%= breadcrumb_title(3) %></a></li>
    <% end %>
</ol>

<!-- <h1 class="h2"><%# @title %><%# " > #{@sub_title}" if @sub_title.present? %></h1> -->