config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  https_constraint = (Rails.env.production? ? {protocol: 'https://'} : {})
  http_catchall    = (Rails.env.production? ? {protocol: 'http://'}  : -> (params, request) {false})

  namespace :api, path: "api", constraints: https_constraint, defaults: { format: 'json' } do
    scope module: :v2, constraints: ApiConstraints.new(version: 2) do
    end
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :devices do
        resources :device_settings, path: 'settings', only: [:index] do
          collection do
            post :bulk_update
          end
        end
        resources :metrics do
          resources :measures
          resources :alerts
        end
        resources :parameters
        resources :strips, only: [:create, :show]
        resources :log_entries, path: 'logs', only: [:create, :index]
        post :brain_upgrade, to: 'brain_upgrade#upgrade'
        post :brain_rollback,  to: "brain_upgrade#rollback"
      end
      namespace :app, path: 'app' do
        post :registration,  to: 'registration#create'
        post :login,         to: 'login#create'
        post :push_update,   to: 'push#create'
      end
    end
  end

  namespace :admin, path: "pastouch", constraints: https_constraint do
    resources :devices do
      member do
        get ':metric', to: 'metrics#show', metric: /(PH|WTEMP|WVOL|ATEMP|AHUM|LCYC|UCYC|NO2|NO3|NH4|GH|KH)/, as: 'metric'
      end
      resources :device_settings do
        patch :prolong_date, to: 'device_settings#prolong_date', on: :member
      end
      resources :log_entries, path: 'logs', only: :index
      resources :device_permissions, path: 'owners'
    end
    resources :users
    mount Resque::Server, at: '/jobs', as: 'jobs'
    root 'devices#index'
  end

  devise_for :users, class_name: 'Risebox::Core::User', path: "account", path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :account, path: "account", constraints: https_constraint do
    get :sso, to: "sso#sso"
  end

  post :sign, to: "signing#sign"
  get :form,  to: "signing#form"

  root 'home#index'

end

app/models/risebox/core/device_setting.rb
class Risebox::Core::DeviceSetting < ActiveRecord::Base
  before_save :update_changed_at

	belongs_to :device, class_name: 'Risebox::Core::Device', foreign_key: :device_id

  def value
    val = self.read_attribute(:value)
    return nil unless val.present?
    case self.data_type
      when 'string'
        val.to_s
      when 'integer'
        val.to_i
      when 'datetime'
        Time.at(val).to_datetime
      else
        val
    end
  end

  def value= val
    self.send('write_attribute', 'value', val.to_f)
  end

private

  def update_changed_at
    self.changed_at = Time.now
  end

end

app/controllers/admin/device_settings_controller.rb
class Admin::DeviceSettingsController < Admin::BaseController

  def index
    @device = Risebox::Core::Device.find_by_key(params[:device_id])
    @settings = @device.settings.all
  end

  def update
  	@device = Risebox::Core::Device.find_by_key(params[:device_id])
  	@setting = @device.settings.find(params[:id])
  	@setting.update_attribute(:value, settings_params[:value])
    redirect_to admin_device_device_settings_path(@device.key)
  end

  def prolong_date
    @device = Risebox::Core::Device.find_by_key(params[:device_id])
    @setting = @device.settings.find(params[:id])
    secs = settings_params[:value].to_i
    @setting.update_attribute(:value, secs.seconds.from_now.to_f)
    redirect_to admin_device_device_settings_path(@device.key)
  end

  def settings_params
  	params.require(:device_setting).permit(:value)
  end

end

app/controllers/api/v1/device_settings_controller.rb
class API::V1::DeviceSettingsController < API::V1::DeviceSecuredController
  skip_before_filter :verify_authenticity_token, only: :bulk_update
  before_action :load_service

  def index
    api_response settings_for_mode(params[:mode], params[:select])
  end

  def bulk_update
    hash = params[:settings]
    hash = JSON.parse(hash) if hash.is_a?(String)
    bulk_updated, bulk_updates = @service.bulk_update(hash)
    api_response [bulk_updated, bulk_updates]
  end

private

  def load_service
    @service = rescuer Risebox::Query::DeviceSetting.new(@device, @brain_calling)
  end

  def settings_for_mode mode, selection
    list = case mode
    when 'full' then @service.full_list
    when 'delta' then @service.delta_list
    when 'select' then @service.select_list selection.split(',')
    else
      @service.full_list
    end
  end

end

app/views/admin/device_settings/index.html.erb
<%= render 'admin/devices/header', device: @device %>

<% breadcrumb([ {title: 'Devices', path: admin_devices_path},
				{title: @device.name.capitalize, path: admin_device_path(@device.key)},
			    {title: 'Settings', path: admin_device_device_settings_path(device_id: @device.key)}
			  ]) %>

<% admin_title 'Device Settings' %>

<div class="table-responsive">
	<table class="table table-hover">
		<tr>
			<th>Clé</th>
			<th>Type</th>
			<th>Valeur</th>
			<th>Changé le</th>
		</tr>
		<% @settings.each do |setting| %>
			<tr>
				<td><strong><%= setting.key %></strong></td>
				<td><%= setting.data_type %></td>
				<td>
					<%= form_for setting, as: :device_setting, url: (setting.data_type == 'datetime' ? prolong_date_admin_device_device_setting_path(device_id: @device.key, id: setting.id) : admin_device_device_setting_path(device_id: @device.key, id: setting.id)) do |f| %>
						<%= f.text_field :value %>
						<%= button_tag class: 'btn btn-default' do %>
                        	<i class="glyphicon glyphicon-save icon-white"></i>&nbsp;<%= setting.data_type == 'datetime' ? 'Ajouter autant de secondes' : 'Modifier la valeur' %>
                    	<% end %>
					<% end %>
				</td>
				<td><%= l(setting.changed_at, format: :long) if setting.changed_at.present? %></td>
			</tr>
		<% end %>
	</table>
</div>