config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  https_constraint = (Rails.env.production? ? {protocol: 'https://'} : {})
  http_catchall    = (Rails.env.production? ? {protocol: 'http://'}  : -> (params, request) {false})

  namespace :api, path: "api", constraints: https_constraint, defaults: { format: 'json' } do
    scope module: :v2, constraints: ApiConstraints.new(version: 2) do
    end
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :devices do
        resources :device_settings, path: 'settings', only: [:index] do
          collection do
            post :bulk_update
          end
        end
        resources :metrics do
          resources :measures
          resources :alerts
        end
        resources :parameters
        resources :strips, only: [:create, :show]
        resources :log_entries, path: 'logs', only: [:create, :index]
        post :brain_upgrade, to: 'brain_upgrade#upgrade'
        post :brain_rollback,  to: "brain_upgrade#rollback"
      end
      namespace :app, path: 'app' do
        post :registration,  to: 'registration#create'
        post :login,         to: 'login#create'
        post :push_update,   to: 'push#create'
      end
    end
  end

  namespace :admin, path: "pastouch", constraints: https_constraint do
    resources :devices do
      member do
        get ':metric', to: 'metrics#show', metric: /(PH|WTEMP|WVOL|ATEMP|AHUM|LCYC|UCYC|NO2|NO3|NH4|GH|KH)/, as: 'metric'
      end
      resources :device_settings do
        patch :prolong_date, to: 'device_settings#prolong_date', on: :member
      end
      resources :log_entries, path: 'logs', only: :index
      resources :device_permissions, path: 'owners'
    end
    resources :users
    mount Resque::Server, at: '/jobs', as: 'jobs'
    root 'devices#index'
  end

  devise_for :users, class_name: 'Risebox::Core::User', path: "account", path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :account, path: "account", constraints: https_constraint do
    get :sso, to: "sso#sso"
  end

  post :sign, to: "signing#sign"
  get :form,  to: "signing#form"

  root 'home#index'

end

app/models/risebox/core/device_permission.rb
class Risebox::Core::DevicePermission < ActiveRecord::Base
	belongs_to :device, class_name: 'Risebox::Core::Device'
	belongs_to :user, class_name: 'Risebox::Core::User'
end

app/controllers/admin/device_permissions_controller.rb
class Admin::DevicePermissionsController < Admin::BaseController

  def index
    @device = Risebox::Core::Device.find_by_key(params[:device_id])
    @permissions = @device.user_permissions
    @other_possible_owner_ids = Risebox::Core::User.where.not(id: @permissions.pluck(:user_id)).map{ |u| [u.pretty_name, u.id] }
  end

  def create
    @device = Risebox::Core::Device.find_by_key(params[:device_id])
    @permission = Risebox::Core::DevicePermission.new(device_permission_params.merge(device_id: @device.id))
    if @permission.save
      flash[:notice] = "Device permission successfully created."
      redirect_to admin_device_device_permissions_path(@device.key)
    else
      render :index
    end
  end

  def destroy
    @device = Risebox::Core::Device.find_by_key(params[:device_id])
    @permission = @device.user_permissions.find(params[:id])
    owner_name = @permission.user.pretty_name
    if @permission.destroy
      flash[:notice] = "#{owner_name} is no longuer an owner of #{@device.key}"
      redirect_to admin_device_device_permissions_path(@device.key)
    else
      flash[:error] = "Error while removing #{owner_name} permission. He is still a owner of #{@device.key}"
    end
  end

private
  def device_permission_params
    params.require(:device_permission).permit(:user_id)
  end

end

app/views/admin/device_permissions/index.html.erb
<%= render 'admin/devices/header', device: @device %>

<% breadcrumb([ {title: 'Devices', path: admin_devices_path},
                {title: @device.name.capitalize, path: admin_device_path(@device.key)},
                {title: 'Owners', path: admin_device_device_permissions_path(device_id: @device.key)}
              ]) %>

<% admin_title 'Device Owners' %>

<%= link_to '#', id: 'addOwnerBtn', class: 'btn btn-primary' do %>
    <i class="glyphicon glyphicon-plus icon-white"></i> Add Owner
<% end %>
<div id="addOwnerDiv" style="display: none;">
    <%= form_for(:device_permission, url: admin_device_device_permissions_path, html: {method: "post", class: 'form-inline'}) do |f| %>
        <div class="form-group">
          <%= f.label  :user_id, nil, class: 'control-label sr-only' %>
          <%= f.select(:user_id, @other_possible_owner_ids, {}, prompt: 'Select another owner', class: 'form-control') %>
        </div>
        <%= f.submit 'Add as owner', class: 'btn btn-success' %>
        <%= link_to 'Cancel', '#', id: 'cancelOwnerBtn' %>
    <% end %>
</div>
<br/><br/>

<div class="table-responsive">
    <table class="table table-hover">
        <tr>
            <th>Nom Prénom</th>
            <th>Propriétaire depuis le</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        <% @permissions.each do |p| %>
            <tr class="clickable-row" data-href='<%= admin_device_device_permission_path(@device.key, p) %>'>
                <td><%= p.user.pretty_name %></td>
                <td><%= l(p.created_at, format: :long) %></td>
                <td>
                    <%= link_to admin_device_device_permissions_path(device_id: @device.key), class: 'btn btn-default' do %>
                        <i class="glyphicon glyphicon-eye-open icon-white"></i> Voir
                    <% end %>
                </td>
                <td>
                    <%= link_to admin_device_device_permission_path(device_id: @device.key, id: p.id), data: { confirm: 'Are you sure' }, method: :delete, class: 'btn btn-danger' do %>
                        <i class="glyphicon glyphicon-trash"></i> Delete
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

<script>
    $('#addOwnerBtn').on('click', function(){
        $('#addOwnerBtn').hide();
        $('#addOwnerDiv').show();
    });
    $('#cancelOwnerBtn').on('click', function(){
        $('#addOwnerDiv').hide();
        $('#addOwnerBtn').show();
    });
</script>