config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  https_constraint = (Rails.env.production? ? {protocol: 'https://'} : {})
  http_catchall    = (Rails.env.production? ? {protocol: 'http://'}  : -> (params, request) {false})

  namespace :api, path: "api", constraints: https_constraint, defaults: { format: 'json' } do
    scope module: :v2, constraints: ApiConstraints.new(version: 2) do
    end
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :devices do
        resources :device_settings, path: 'settings', only: [:index] do
          collection do
            post :bulk_update
          end
        end
        resources :metrics do
          resources :measures
          resources :alerts
        end
        resources :parameters
        resources :strips, only: [:create, :show]
        resources :log_entries, path: 'logs', only: [:create, :index]
        post :brain_upgrade, to: 'brain_upgrade#upgrade'
        post :brain_rollback,  to: "brain_upgrade#rollback"
      end
      namespace :app, path: 'app' do
        post :registration,  to: 'registration#create'
        post :login,         to: 'login#create'
        post :push_update,   to: 'push#create'
      end
    end
  end

  namespace :admin, path: "pastouch", constraints: https_constraint do
    resources :devices do
      member do
        get ':metric', to: 'metrics#show', metric: /(PH|WTEMP|WVOL|ATEMP|AHUM|LCYC|UCYC|NO2|NO3|NH4|GH|KH)/, as: 'metric'
      end
      resources :device_settings do
        patch :prolong_date, to: 'device_settings#prolong_date', on: :member
      end
      resources :log_entries, path: 'logs', only: :index
      resources :device_permissions, path: 'owners'
    end
    resources :users
    mount Resque::Server, at: '/jobs', as: 'jobs'
    root 'devices#index'
  end

  devise_for :users, class_name: 'Risebox::Core::User', path: "account", path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }

  namespace :account, path: "account", constraints: https_constraint do
    get :sso, to: "sso#sso"
  end

  post :sign, to: "signing#sign"
  get :form,  to: "signing#form"

  root 'home#index'

end

app/models/risebox/core/user.rb
class Risebox::Core::User < ActiveRecord::Base
  has_many :devices_permissions, class_name: 'Risebox::Core::DevicePermission'
  has_many :devices, class_name: 'Risebox::Core::Device', through: :devices_permissions
  has_many :registrations, class_name: 'Risebox::Core::AppRegistration'
  has_many :push_tokens, through: :registrations, class_name: 'Risebox::Core::PushToken'

  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :trackable, :timeoutable, :validatable
  #:confirmable,

  before_validation :generate_password_if_not_set_and_not_human
  before_create :generate_api_token

  def generate_api_token
    begin
      self.api_token = SecureRandom.hex
    end while self.class.exists?(api_token: api_token)
    self.api_token
  end

  def generate_password_if_not_set_and_not_human
  	return unless password.nil? && !human
  	psw = SecureRandom.hex
  	self.password = psw
  	self.password_confirmation = psw
  end

  def pretty_name
    "#{first_name.try(:capitalize)} #{last_name.try(:capitalize)}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = Risebox::Core::User.order(created_at: :desc)
  end

  def show
    @user = Risebox::Core::User.find(params[:id])
  end

  def new
    @user = Risebox::Core::User.new
  end

  def create
    @user = Risebox::Core::User.new(user_params)
    if @user.save
      flash[:notice] = "User successfully created."
      redirect_to admin_user_path(@user)
    else
      puts "@user.errors #{@user.errors.to_yaml}"
      render :new
    end
  end

  def edit
    @user = Risebox::Core::User.find(params[:id])
  end

  def update
    @user = Risebox::Core::User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "User successfully updated."
      redirect_to admin_user_path(@user)
    else
      puts "@user.errors #{@user.errors.to_yaml}"
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:human, :first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/admin/users/_form.html.erb
<%# f.error_messages %>

<div class="form-group">
  <%= f.label      :type, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10 ">
    <div class="btn-group" role="group" aria-label="user-type" data-toggle="buttons">
      <label class="btn btn-default <%='active' if f.object.human? %>">
        <%= f.radio_button :human, true, autocomplete: :off %> User
      </label>
      <label class="btn btn-default <%='active' if !f.object.human? %>">
        <%= f.radio_button :human, false, autocomplete: :off %> Brain
      </label>
    </div>
  </div>
</div>

<div class="form-group">
  <%= f.label      :first_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10 ">
      <%= f.text_field(:first_name, class: 'form-control', placeholder: 'First Name') %>
  </div>
</div>

<div class="form-group">
  <%= f.label      :last_name, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field(:last_name, class: 'form-control', placeholder: 'Last Name') %>
  </div>
</div>

<div class="form-group">
  <%= f.label      :email, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.email_field(:email, class: 'form-control', placeholder: 'Email') %>
  </div>
</div>

<div class="form-group">
  <%= f.label      :password, class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.password_field(:password, class: 'form-control', placeholder: 'Password') %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-2">&nbsp;</div>
  <div class="col-sm-10">
    <%= f.password_field(:password_confirmation, class: 'form-control', placeholder: 'Type your password again') %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit btn_text, class: 'btn btn-success' %>
    &nbsp;
    <%= link_to "Cancel", :back %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% breadcrumb([ {title: 'Users', path: admin_users_path},
                {title: @user.pretty_name, path: admin_users_path(@user)},
                {title: 'Edit',   path: edit_admin_user_path} ]) %>

<%= form_for(@user, as: :user, url: admin_user_path(@user), html: {method: "put", class: 'form-horizontal'}) do |f| %>

  <%= render 'form', f: f, btn_text: "Update User" %>

<% end %>

app/views/admin/users/index.html.erb
<% admin_title 'Users', 'List' %>

<% breadcrumb([ {title: 'Users', path: admin_users_path()} ]) %>

<%= link_to new_admin_user_path, class: 'btn btn-primary' do %>
    <i class="glyphicon glyphicon-plus icon-white"></i> Add User
<% end %>
<br/><br/>

<div class="table-responsive">
    <table class="table table-hover">
        <tr>
            <th>Type</th>
            <th>Nom</th>
            <th>Email</th>
            <th>&nbsp;</th>
        </tr>
        <% @users.each do |user| %>
            <tr class="clickable-row" data-href='<%= admin_users_path(id: user.id) %>'>
                <td><%= raw user_label(user) %></td>
                <td><%= user.pretty_name %></td>
                <td><%= user.email %></td>
                <td>
                    <%= link_to admin_user_path(user), class: 'btn btn-default' do %>
                        <i class="glyphicon glyphicon-eye-open icon-white"></i> Voir
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/admin/users/new.html.erb
<% breadcrumb([ {title: 'Users', path: admin_users_path},
                {title: 'New',   path: new_admin_user_path} ]) %>

<%= form_for(@user, as: :user, url: admin_users_path, html: {method: "post", class: 'form-horizontal'}) do |f| %>

  <%= render 'form', f: f, btn_text: "Add User" %>

<% end %>

app/views/admin/users/show.html.erb
<% admin_title 'Users', @user.pretty_name %>

<% breadcrumb([ {title: 'Users', path: admin_users_path()},
                {title: @user.pretty_name, path: admin_users_path(@user)} ]) %>


<%= link_to edit_admin_user_path(@user), class: 'btn btn-default' do %>
    <i class="glyphicon glyphicon-pencil icon-white"></i>&nbsp; Edit user
<% end %>